name: Execute extract_funds_data.py

on:
  push:
    branches:
      - main  # Ejecuta cuando se hace push en la rama main
  schedule:
    # Ejecutar a las 13:30 y 18:30 hora Perú (UTC-5)
    - cron: "30 18 * * 1-4"  # 18:30 UTC (13:30 hora Perú)
    - cron: "30 23 * * 1-4"  # 23:30 UTC (18:30 hora Perú)
  workflow_dispatch: # Permite ejecución manual desde GitHub Actions

permissions:
  contents: write  # Permiso para hacer git pull, commit y push

jobs:
  execute-python-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Permisos para escritura
      # 2. Configurar caché para dependencias de Python
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Cambia según tu versión de Python

      # 4. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Ejecutar el script
      - name: Execute extract_funds_data.py
        run: |
          python InterFondos/interbank/extract_funds_data.py

      # 6. Actualizar repositorio con el CSV generado
      - name: Push changes to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
          git add -A
          git commit -m "Update CSV"
          git push origin main
